import { IENV } from "@/types/env";

let variable: IENV = {
  APPWRITE_ENDPOINT: "",
  APPWRITE_PLATFORM: "",
  APPWRITE_PROJECT: "",
  DATABASE_PRIMARY: "",
  COLLECTION_USER_INFO: "",
  COLLECTION_POST_INFO: "",
  COLLECTION_LINE_INFO: "",
  COLLECTION_LINE_SUBSCRIPTION: "",
  COLLECTION_NOTIFICATION_INFO: "",
  BUCKET_IMAGE: "",
  FUNCTION_NOTIFICATION: "",
  FUNCTION_USER: "",
  WEBAPP_ENDPOINT: "",
  COLLECTION_USER_ACTIVITY: "",
};

if (__DEV__) {
  variable = {
    APPWRITE_ENDPOINT: process.env.EXPO_PUBLIC_APPWRITE_ENDPOINT!,
    APPWRITE_PLATFORM: process.env.EXPO_PUBLIC_APPWRITE_PLATFORM!,
    APPWRITE_PROJECT: process.env.EXPO_PUBLIC_APPWRITE_PROJECT!,
    DATABASE_PRIMARY: process.env.EXPO_PUBLIC_DATABASE_PRIMARY!,
    COLLECTION_USER_INFO: process.env.EXPO_PUBLIC_COLLECTION_USER_INFO!,
    COLLECTION_USER_ACTIVITY: process.env.EXPO_PUBLIC_COLLECTION_USER_ACTIVITY!,
    COLLECTION_POST_INFO: process.env.EXPO_PUBLIC_COLLECTION_POST_INFO!,
    COLLECTION_LINE_INFO: process.env.EXPO_PUBLIC_COLLECTION_LINE_INFO!,
    COLLECTION_LINE_SUBSCRIPTION:
      process.env.EXPO_PUBLIC_COLLECTION_LINE_SUBSCRIPTION!,
    COLLECTION_NOTIFICATION_INFO:
      process.env.EXPO_PUBLIC_COLLECTION_NOTIFICATION_INFO!,
    BUCKET_IMAGE: process.env.EXPO_PUBLIC_BUCKET_IMAGE!,
    FUNCTION_NOTIFICATION: process.env.EXPO_PUBLIC_FUNCTION_NOTIFICATION!,
    FUNCTION_USER: process.env.EXPO_PUBLIC_FUNCTION_USER!,
    WEBAPP_ENDPOINT: process.env.EXPO_PUBLIC_WEBAPP_ENDPOINT!,
  };
} else {
  variable = {
    APPWRITE_ENDPOINT: process.env.APPWRITE_ENDPOINT!,
    APPWRITE_PLATFORM: process.env.APPWRITE_PLATFORM!,
    APPWRITE_PROJECT: process.env.APPWRITE_PROJECT!,
    DATABASE_PRIMARY: process.env.DATABASE_PRIMARY!,
    COLLECTION_USER_INFO: process.env.COLLECTION_USER_INFO!,
    COLLECTION_USER_ACTIVITY: process.env.COLLECTION_USER_ACTIVITY!,
    COLLECTION_POST_INFO: process.env.COLLECTION_POST_INFO!,
    COLLECTION_LINE_INFO: process.env.COLLECTION_LINE_INFO!,
    COLLECTION_LINE_SUBSCRIPTION: process.env.COLLECTION_LINE_SUBSCRIPTION!,
    COLLECTION_NOTIFICATION_INFO: process.env.COLLECTION_NOTIFICATION_INFO!,
    BUCKET_IMAGE: process.env.BUCKET_IMAGE!,
    FUNCTION_NOTIFICATION: process.env.FUNCTION_NOTIFICATION!,
    FUNCTION_USER: process.env.FUNCTION_USER!,
    WEBAPP_ENDPOINT: process.env.WEBAPP_ENDPOINT!,
  };
}

export const env = variable;
