export interface IENV {
  APPWRITE_ENDPOINT: string;
  APPWRITE_PLATFORM: string;
  APPWRITE_PROJECT: string;
  DATABASE_PRIMARY: string;
  COLLECTION_USER_INFO: string;
  COLLECTION_POST_INFO: string;
  COLLECTION_LINE_INFO: string;
  COLLECTION_LINE_SUBSCRIPTION: string;
  COLLECTION_NOTIFICATION_INFO: string;
  BUCKET_IMAGE: string;
  FUNCTION_NOTIFICATION: string;
  FUNCTION_USER: string;
  WEBAPP_ENDPOINT: string;
}
